import { ANIMS } from '../anims/anims.js';

// ---- Moveset table ----
// the skills that play on another move's frames (or on none) get their own rows after the animations
const SKILL_ROWS = [
  ['hold I · Thousand Cuts', 'Hold I in the double slash\'s crouch (about 0.9 s to full) while his body gathers light, then let go: he vanishes to a point ahead and blinks round it seven times in about 0.3 s, a cyan afterimage and a crescent in a new direction at each spot, then lands the final double cut. Everything in a wide circle round the point is hit and bursts on the sheath click. Range and area grow with the charge; aim with the arrows while holding.'],
  ['P · Cross Rift', 'The dash, the two crossing cuts, the freeze and the resheathe of the double slash. The cuts open into a giant X of torn reality: jagged slits of void with crawling, flickering lips, star-specks drifting inside, stone chips and motes pulled into it. On the sheath click it snaps shut, implodes for three frames, then detonates outward in a white ring that hits everything inside. Tap for a mid-size rift, hold to charge a bigger one.'],
  ['Qi · Storm Chain', 'A passive. Every hit he lands fills the Qi meter at the bottom left (bigger moves fill more); out of the fight it slowly ebbs. When it fills, Storm Chain wakes for 8 s: the meter glows and crackles, bolts run over his body, and every hit he lands leaps as lightning from the struck enemy to up to three enemies nearby, hitting each. Then the meter empties.'],
  ['Skill cooldowns', 'A row of small slots under health and Qi: I, O, P, N and U, then K and slide. Every active has a cooldown, shown as a shade draining upward over its icon with the seconds left; a key pressed too soon does nothing and its slot blinks. K 3 s (none with no enemy near, and only 0.2 s after an assassination), I 2 s (Thousand Cuts 8 s), O 10 s, P 12 s, N 14 s, U 8 s, slide 1 s. O, P and Thousand Cuts start cooling down when you let go.'],
  ['HUD · items', 'Top left: health (white, blinking red under 35%) and Qi (cyan, notched in thirds). Top right: mon and glitch shards. Bottom: the weapon slot, quick slots 1-4 and four charm slots. Big items (shrine, grave blade, sealed chest, rift tablet) lock on with cyan brackets and an E prompt when he is close; small pickups fly to him; relics hover until he walks into them, then fly to an empty charm slot.'],
  ['Relics · charm slots', 'Thunder Bead: Storm Chain jumps one more. Cracked Mirror: each glitch teleport leaves an afterimage that cuts once. Split Tsuba: landed hits build 25% more Qi. Temple Bell (+25% Qi per execution), Paper Crane (once per area a killing blow leaves you at 1 health) and Sageo Knot (the sheath click after a kill shocks enemies nearby) wait on real kills and damage.'],
  ['Power I · II · III', 'Every skill has three versions, and power also scales stats: Qi from hits +15% / +30%, cooldowns -10% / -20% (damage x1.25 / x1.5 once enemies have health). II lifts stone off the floor as a skill fires; III adds ribbons of light. Storm Chain: 3 / 4 / 5 jumps and 8 / 9 / 10 s. Thousand Cuts: 7 / 9 / 11 cuts. Cross Rift: a bigger X at II, a second detonation at III. Crescent Moon: the shatter cuts at II, a twin moon the other way at III. Mirror Meditation: one / two more images. Storm slam: 20% wider at II, bolts out of the cracks at III.'],
];
export function fillMoveset() {
  document.getElementById('moves').innerHTML = [...Object.entries(ANIMS).filter(([, a]) => !a.hidden).map(([k, a]) => [k, a.about]), ...SKILL_ROWS]
    .map(([k, a]) => `<tr><td>${k}</td><td>${a}</td></tr>`).join('');
}
