import { ANIMS } from '../anims/anims.js';

// ---- Moveset table ----
// the skills that play on another move's frames (or on none) get their own rows after the animations
const SKILL_ROWS = [
  ['Weapons', 'The picker under the game switches weapon: katana, yari, nodachi, twin tanto. Every move works with every weapon on the same timing and hits; each weapon brings its own poses for the cuts, the guard and the six stances, and is stowed its own way (the katana at the hip, the yari and nodachi on his back, the tanto at the obi). Reach and weight differ too: the nodachi reaches further and every hit holds a longer pause and shake; the yari reaches furthest; the tanto is short and light.'],
  ['hold I · Thousand Cuts', 'Hold I in the double slash\'s crouch (about 0.9 s to full) while his body gathers light, then let go: he vanishes to a point ahead and blinks round it seven times in about 0.3 s, a cyan afterimage and a crescent in a new direction at each spot, then lands the final double cut. Everything in a wide circle round the point is hit and bursts on the sheath click. Range and area grow with the charge; aim with the arrows while holding.'],
  ['P · Cross Rift', 'The dash, the two crossing cuts, the freeze and the resheathe of the double slash. The cuts open into a giant X of torn reality: jagged slits of void with crawling, flickering lips, star-specks drifting inside, stone chips and motes pulled into it. On the sheath click it snaps shut, implodes for three frames, then detonates outward in a white ring that hits everything inside. Tap for a mid-size rift, hold to charge a bigger one.'],
  ['J combo · basic skill', 'Every basic cut that lands grows his basic skill. He starts with the two-cut combo; at 40, 120, 250 and 450 landed cuts the chain runs to three, four, five and six cuts, each weapon with its own. Press J again during a cut\'s follow-through to flow into the next. Under the skill slots, J2 to J6 shows how far it runs now. The Basic skill picker under the game jumps straight to a length for testing.'],
  ['Flow', 'A passive. Chain any six basic cuts (across short combos is fine, each landing within 1.6 s of the last, no skill in between) and six pips under the skill slots fill. For 8 s the next skill still cooling down casts anyway: K, I or Thousand Cuts, O, P, N or U, and then cools down again from the start. A skill that is ready casts as usual and Flow keeps. Never the slide, and never an ultimate (Time Slice, the full-Qi skills).'],
  ['Qi · Storm Chain', 'A passive. Every hit he lands fills the Qi meter at the bottom left (bigger moves fill more); out of the fight it slowly ebbs. When it fills, Storm Chain wakes for 8 s: the meter glows and crackles, bolts run over his body, and every hit he lands leaps as lightning from the struck dummy to up to three dummies nearby, hitting each. Then the meter empties.'],
  ['Skill cooldowns', 'A row of small slots under health and Qi: I, O, P, N and U, then K and slide. Every active has a cooldown, shown as a shade draining upward over its icon with the seconds left; a key pressed too soon does nothing and its slot blinks. K 3 s (none with no enemy near, and only 0.2 s after an assassination), I 2 s (Thousand Cuts 8 s), O 10 s, P 12 s, N 14 s, U 8 s, slide 1 s. O, P and Thousand Cuts start cooling down when you let go.'],
  ['HUD · items', 'Top left: health (white, blinking red under 35%) and Qi (cyan, notched in thirds). Top right: mon and glitch shards. Bottom: the weapon slot, quick slots 1-4 and four charm slots. Big items (shrine, grave blade, sealed chest, rift tablet) lock on with cyan brackets and an E prompt when he is close; small pickups fly to him; relics hover until he walks into them, then fly to an empty charm slot.'],
  ['Relics · charm slots', 'Thunder Bead: Storm Chain jumps one more. Cracked Mirror: each glitch teleport leaves an afterimage that cuts once. Split Tsuba: landed hits build 25% more Qi. Temple Bell (+25% Qi per execution), Paper Crane (once per area a killing blow leaves you at 1 health) and Sageo Knot (the sheath click after a kill shocks enemies nearby) wait on real kills and damage.'],
];
export function fillMoveset() {
  document.getElementById('moves').innerHTML = [...Object.entries(ANIMS).filter(([, a]) => !a.hidden).map(([k, a]) => [k, a.about]), ...SKILL_ROWS]
    .map(([k, a]) => `<tr><td>${k}</td><td>${a}</td></tr>`).join('');
}
