// ---- Animations: timing lives here, art comes from a sheet (placeholder or dropped strip) ----
export const ANIMS = {
  idle:     { n: 16, fps: 6,  loop: true,  about: 'A calm breath, about 2.7 s: the chest and shoulders rise a pixel while the hips stay planted, and the mantle barely stirs. His hands hang free and the katana stays sheathed at his hip.' },
  idleGlitch:{ n: 8, fps: 14, loop: false, about: 'After 4 s standing still he glitches once, then back to idle.' },
  run:      { n: 8,  fps: 14, loop: true,  about: 'Leaning into the run with the arms swinging and the katana sheathed at the hip. Faces left or right by the last sideways input.' },
  slide:    { n: 10, fps: 20, loop: false, about: 'Replaces wall slide: a push-off step, then he drops and glides leaning back, lead leg straight, back leg folded under, back arm raised behind for balance while the hat slips back. Momentum carries him up out of it.' },
  jump:     { n: 4,  fps: 12, loop: false, about: 'A hop off the floor with the knees tucked. You can steer in the air. His shadow and reflection stay on the ground.' },
  fall:     { n: 3,  fps: 12, loop: true,  about: 'The way down from a jump, the back arm up.' },
  land:     { n: 3,  fps: 16, loop: false, about: 'Touchdown: knees soak it up, with a dust puff.' },
  slash1:   { n: 16, fps: 30, loop: false, about: 'One fluid cut, 0.5 s: from the sheath, the hips sink and the chest turns away, then hips, chest, arms and blade drive through in that order with a lunge, into a held follow-through, and he settles into his guard stance. Press J again during the follow-through to flow straight into slash 2.' },
  slash1r:  { n: 16, fps: 30, loop: false, hidden: true, about: '' },
  ready:    { n: 16, fps: 8,  loop: true,  about: 'Waiting with the blade out after an attack. Each time, one of six stances is picked at random: four side-on counter stances (low hang, reverse grip, tip to the floor, shoulder first) with the blade in his back hand pointing at the ground, and two opened to the camera (open, invitation). After about 2 s of calm he resheathes.' },
  ready0:   { n: 16, fps: 8,  loop: true,  hidden: true, about: '' },
  ready1:   { n: 16, fps: 8,  loop: true,  hidden: true, about: '' },
  ready2:   { n: 16, fps: 8,  loop: true,  hidden: true, about: '' },
  ready3:   { n: 16, fps: 8,  loop: true,  hidden: true, about: '' },
  ready4:   { n: 8,  fps: 4,  loop: true,  hidden: true, about: '' },
  ready5:   { n: 8,  fps: 4,  loop: true,  hidden: true, about: '' },
  runArmed: { n: 8,  fps: 14, loop: true,  about: 'Running with the blade out, trailing low behind him.' },
  slash2:   { n: 16, fps: 30, loop: false, about: 'The answer cut, flowing on from slash 1\'s follow-through: he sinks and coils, then rises through a cut that ends with the blade overhead and the chest open, and settles back into guard.' },
  sheathe:  { n: 19, fps: 15, loop: false, about: 'Unhurried, 1.2 s, only once he has waited in guard: a sharp flick, a beat, the blade laid across and slid home slowly, the click, a moment of stillness, then his hands let go.' },
  tele:     { n: 8,  fps: 22, loop: false, about: 'Glitch teleport: he drops into a sprinter\'s crouch and breaks into slices, blinks 56 px, and lands kneeling in a flurry of crackling electricity before rising. For a few seconds afterwards his body glitches at random, as if the jump is still settling. Glitch slivers hang at both ends.' },
  double:   { n: 16, fps: 24, loop: false, about: 'Glitch double slash: a deep quick-draw crouch, vanish, then a long low lunge cut and a second cut down past his body. He freezes in the final pose, sheathes, and on the click the target bursts. That is a tap of I. Hold I instead to charge Thousand Cuts in this crouch; P (Cross Rift) plays on these frames too.' },
  sweep:    { n: 44, fps: 20, loop: false, about: 'Storm slam: he kneels slowly and draws, then waits a full second gathering power. Chips of stone and dust lift off the floor, drift in and circle him, faster and faster, with crackles jumping between them. He rises with the blade whirling in a cyclone, the debris spiralling up with him, leaps, and brings the blade all the way down. The slam flings the debris out, cracks the floor, throws a ring of bolts and shakes the screen.' },
  moonHold: { n: 8,  fps: 10, loop: true,  about: 'Crescent Moon, the charge (hold O): he plants his feet and raises the blade high behind his head, in place. Sparks and short bolts gather onto his body, a cyan rim flickers round him and motes rise off his hat and shoulders, all growing with the charge (about 0.9 s to full).' },
  moon:     { n: 24, fps: 30, loop: false, about: 'Crescent Moon, the release: one huge descending cut. A giant crescent sweeps into being along its arc in about 0.15 s: white-hot core, cyan body, a flickering pale shimmer, echoes and motes trailing off it, a pale screen flash, a shockwave on the floor and its light pooled beneath. It hangs, glowing, then shatters into slivers and shards and everything under it bursts. Size and power grow with the charge. He settles into guard.' },
  meditate: { n: 16, fps: 12, loop: true,  about: 'Mirror Meditation (N): he stands still without drawing, palms together at his chest, head bowed, eyes dimmed, breathing slowly inside a faint cyan aura. For about 1.4 s he cannot move while 3 to 5 glitching cyan mirror images step out of him, each dash to a different nearest dummy, cut it once and dissolve into slivers. Mirror hits feed Qi.' },
  sitDown:  { n: 4,  fps: 8,  loop: false, about: 'Replaces wall sit: he turns his back to the camera and lowers himself to the floor.' },
  standUp:  { n: 4,  fps: 12, loop: false, about: 'Getting up from the monk sit: he rises, stands with his back to you, then turns. Plays before anything he does from sitting.' },
  sit:      { n: 8,  fps: 3,  loop: true,  about: 'Sitting cross-legged like a monk, back to the camera, katana laid beside him, breathing slowly. Any move gets him up.' },
  death:    { n: 10, fps: 10, loop: false, about: 'Recoils, drops to a knee, falls forward and glitches apart. He comes back a second later.' },
  // items (prototypes/20-items.html): E at a big item, 1-4 for the quick slots, hold E for Harvest
  pray:     { n: 1, fps: 20, loop: false, about: 'E at a Wayside Shrine: he kneels and prays while its light leaves the flame in motes and arcs into his chest; health and Qi fill to full. Once per shrine, then its light goes out.' },
  take:     { n: 1, fps: 30, loop: false, about: 'E at the Grave Nodachi: he grips the hilt and pulls it from the grave in one jerk (a cut of light, dust, a crack), holds it up, flicks and sheathes. The weapon slot swaps and flashes, and NEW WEAPON / GRAVE NODACHI shows. Longer reach, and every cut lands a beat heavier.' },
  cutSeal:  { n: 1, fps: 30, loop: false, about: 'E at a Sealed Chest: one draw splits the paper seal; on the sheath click the seal falls in two, the lid pops and it spills mon and Qi, which fly to him.' },
  read:     { n: 1, fps: 20, loop: false, about: 'E at a Rift Tablet: a palm on the stone, the glyphs light in order, then leave the stone and fly into him. SKILL LEARNED / CROSS RIFT.' },
  bomb:     { n: 1, fps: 30, loop: false, about: 'Quick slot, Static Bomb: he dashes a clay ball at his feet; it bursts into a cloud of black static crackling with cyan, and he glitches a few steps back out of it. The smoke rolls out to fill the whole screen for 6 s: enemies lose him, and every one of them counts as isolated, so K can take any of them with its 0.2 s reset.' },
  talisman: { n: 1, fps: 30, loop: false, about: 'Quick slot, Thunder Talisman: he raises the paper; lightning strikes the nearest enemy and jumps once to the next, like Storm Chain, at no Qi cost.' },
  whet:     { n: 1, fps: 30, loop: false, about: 'Quick slot, Whetstone: he draws and hones the blade with sparks running along it, and the edge turns cyan for 20 s (a timer on the slot). Cuts build Qi twice as fast. He keeps it out, in guard.' },
  incense:  { n: 1, fps: 20, loop: false, about: 'Quick slot, Grave Incense: he kneels and lights a stick; pale threads rise and curl into him as he heals 60% over 1.5 s. Moving or a hit puts it out.' },
  harvest:  { n: 1, fps: 8,  loop: true,  about: 'Hold E near the fallen: he plants his feet, opens his palms and lets their remains stream into him as EXP; a level-up shows LEVEL UP / LV n. Side view until the 8-direction rig lets him face north. Tap E is the item verb, hold E is Harvest.' },
};
export const GLITCHY = new Set(['idleGlitch', 'tele', 'double']);
