// ---- Personality traits: each is only data, nudging the knobs in knobs.js ----
// all: applies to idle, walk and run (only where the knob exists); idle / walk / run: that mode only.
// Numbers add to BASE (period, fps and speed multiply). f / b: hand targets from ARMS, by weight.
// fidgets: idle actions from fidgets.js. like: starts from another trait and adds these nudges on top.
// A character mixes traits with strengths, e.g. [['proud', 1], ['elder', .5]]; see mix.js.
export const TRAITS = {
  // -- bearing: how he carries himself
  stoic: { name: 'Stoic', group: 'bearing', about: 'Barely moves. A shallow breath, a rare glance at his blade, an even, quiet step.',
    idle: { breath: -.4, every: 4 }, walk: { bounce: -.42, swing: -.14 }, run: { swing: -.21 }, fidgets: ['hiltCheck'] },
  proud: { name: 'Proud', group: 'bearing', about: 'Chest out, chin up, hands clasped behind him. Long, unhurried strides.',
    all: { lean: -.16, chest: -.14, bow: -.52 }, idle: { legs: .6, b: { behind: 1 } }, walk: { stride: .24, fps: .84, swing: -.21, b: { behind: 1 } }, fidgets: ['glance'] },
  humble: { name: 'Humble', group: 'bearing', about: 'Head dipped, hands folded low in front of him. Small, polite steps.',
    all: { bow: .75, lean: .1 }, idle: { f: { folded: 1 }, b: { folded: 1 } }, walk: { stride: -.19, fps: .84, swing: -.21, f: { folded: .7 } }, fidgets: ['nod'] },
  regal: { name: 'Regal', group: 'bearing', about: 'Upright and still, both hands behind his back. A slow, level walk with no bounce at all.',
    all: { lean: -.12, chest: -.07, bow: -.3 }, idle: { breath: -.3, f: { behind: 1 }, b: { behind: 1 } },
    walk: { fps: .68, stride: .16, bounce: -.84, f: { behind: 1 }, b: { behind: 1 } }, run: { fps: .87 }, fidgets: ['nod'] },
  hunched: { name: 'Hunched', group: 'bearing', about: 'Rounded over, head low, as if under a weight. Short steps.',
    all: { lean: .44, chest: .22, bow: .9 }, idle: { fa: [.1, .2], ba: [.1, .2] }, walk: { stride: -.16, lift: -.2 }, run: { lean: .16 } },
  coiled: { name: 'Coiled', group: 'bearing', about: 'Always half a breath from drawing: knees bent, feet wide, hand on the hilt. Stalks rather than walks.',
    all: { lean: .24 }, idle: { knee: 1.12, legs: 2, breath: -.3, f: { hilt: 1 } }, walk: { knee0: .56, bounce: -.56, stride: .16, fps: .76, f: { hilt: 1 } },
    run: { lean: .2, f: { hilt: .8 } }, fidgets: ['hiltThumb'] },
  slouch: { name: 'Slouched', group: 'bearing', about: 'Hips pushed forward, shoulders back, arms hanging. Scuffs along.',
    all: { lean: -.2, chest: .32, bow: .52, hx: 1 }, idle: { f: { dangle: .6 }, b: { dangle: .6 } }, walk: { swing: -.14, lift: -.26, bounce: -.28 }, fidgets: ['sigh'] },
  soldier: { name: 'Soldier', group: 'bearing', about: 'Drilled: feet together, still as a post, then a crisp march with the arms swinging high.',
    all: { lean: -.04, chest: -.07 }, idle: { breath: -.5, legs: -.5, every: 6 }, walk: { swing: .49, lift: .33, fps: 1.16, faEl: -.2, baEl: -.2, bounce: .28, f: { hilt: -.6 } },
    run: { swing: .14 } },

  // -- energy: how much he has left
  lazy: { name: 'Lazy', group: 'energy', about: 'Arms dead at his sides, slow deep breaths, a yawn now and then. Drags his feet.',
    all: { bow: .45, lean: -.08 }, idle: { period: 1.35, breath: .3, hx: 1, f: { dangle: 1 }, b: { dangle: 1 } },
    walk: { fps: .52, lift: -.45, stride: -.16, swing: -.21, bounce: -.42, speed: .8 }, run: { fps: .76, lift: -.39, speed: .9 }, fidgets: ['yawn'] },
  restless: { name: 'Restless', group: 'energy', about: 'Can\'t stand still: sways, taps his foot, shifts his weight, and fidgets every breath.',
    idle: { sway: 1.3, jitter: .48, every: -1 }, walk: { fps: 1.16 }, fidgets: ['footTap', 'weightShift'] },
  twitchy: { name: 'Twitchy', group: 'energy', about: 'Quick shallow breaths and little jerks. Glances round, shakes out his hand.',
    idle: { jitter: 1.44, period: .8, every: -1 }, walk: { fps: 1.32, wobble: .2 }, run: { fps: 1.16 }, fidgets: ['glance', 'flexHand'] },
  bouncy: { name: 'Bouncy', group: 'energy', about: 'Springs on his knees with each breath and bounds when he walks.',
    idle: { bob: 1, period: .8, knee: .28 }, walk: { bounce: 1.96, lift: .39, fps: 1.16 }, run: { bounce: 1.4 }, fidgets: ['toes'] },
  weary: { name: 'Weary', group: 'energy', about: 'Bone tired: heavy breaths, head down, arms hanging. Every footfall lands hard.',
    all: { bow: .9, lean: .24, chest: .14 }, idle: { breath: .8, period: 1.2, knee: .21, f: { dangle: .7 }, b: { dangle: .7 } },
    walk: { fps: .6, stride: -.19, lift: -.39, swing: -.21, heavy: 1.04, speed: .75 }, run: { fps: .76, speed: .85, lift: -.39 }, fidgets: ['sigh'] },
  eager: { name: 'Eager', group: 'energy', about: 'Leaning in, up on the balls of his feet, quick to go.',
    all: { lean: .2, bow: -.22 }, idle: { bob: .5, period: .85, knee: .21 }, walk: { fps: 1.32, stride: .16, speed: 1.15 },
    run: { speed: 1.1, lean: .16, fps: 1.08 }, fidgets: ['toes'] },
  heavy: { name: 'Heavy', group: 'energy', about: 'Wide and solid. Rolls his shoulders; every step thuds.',
    all: { lean: .06 }, idle: { legs: 1.5, knee: .28, breath: .3 }, walk: { heavy: 1.95, fps: .68, stride: .08, speed: .85 },
    run: { heavy: 1.56, fps: .76 }, fidgets: ['shoulderRoll'] },
  lightFooted: { name: 'Light-footed', group: 'energy', about: 'Barely touches the floor: no bounce, high quick feet.',
    idle: { knee: .14 }, walk: { bounce: -.7, lift: .26, fps: 1.16 }, run: { bounce: -.56, lift: .26, speed: 1.08 }, fidgets: ['toes'] },

  // -- mood: what he feels
  calm: { name: 'Calm', group: 'mood', about: 'Slow, even breathing, few fidgets, a gentle unhurried walk.',
    idle: { period: 1.3, breath: -.2, every: 2 }, walk: { fps: .84, bounce: -.28 } },
  nervous: { name: 'Nervous', group: 'mood', about: 'Hand never leaves the hilt. Shrinks a little, glances round, quick short steps.',
    all: { bow: .3, lean: .12 }, idle: { jitter: .6, every: -1, knee: .28, legs: -.3, f: { hilt: .9 } },
    walk: { fps: 1.24, stride: -.16, f: { hilt: 1 } }, fidgets: ['glance', 'hiltThumb'] },
  cocky: { name: 'Cocky', group: 'mood', about: 'Fist on his hip, hat pushed back, a swagger in every step.',
    all: { lean: -.16, chest: -.11, bow: -.3, hat: -1 }, idle: { legs: 1.5, sway: .78, b: { hip: 1 } },
    walk: { rock: 1.6, fps: .84, stride: .16, bounce: .42, b: { hip: 1 } }, run: { rock: .8 }, fidgets: ['dustOff', 'neckCrack'] },
  brooding: { name: 'Brooding', group: 'mood', about: 'Arms folded, head sunk, staring at nothing.',
    all: { bow: 1.2, lean: .04 }, idle: { breath: -.2, f: { cross: 1 }, b: { cross: 1 } }, walk: { fps: .68, stride: -.13, f: { cross: 1 }, b: { cross: 1 } }, fidgets: ['lookDown'] },
  cheerful: { name: 'Cheerful', group: 'mood', about: 'Chin up, a little sway, a springy walk with big arm swings.',
    all: { bow: -.38 }, idle: { bob: .6, sway: 1.04 }, walk: { bounce: 1.12, swing: .35, fps: 1.16, f: { hilt: -.6 } }, run: { swing: .14, bounce: .56 }, fidgets: ['toes', 'stretch'] },
  grim: { name: 'Grim', group: 'mood', about: 'Feet set, hand on the hilt, jaw down. A heavy, deliberate walk.',
    all: { bow: .45, lean: .08 }, idle: { breath: -.4, every: 2, legs: .6, f: { hilt: 1 } }, walk: { heavy: .78, fps: .76, swing: -.21, f: { hilt: 1 } }, fidgets: ['hiltCheck'] },
  wary: { name: 'Wary', group: 'mood', about: 'Half crouched, weight ready, checking behind him.',
    all: { lean: .12 }, idle: { knee: .49, legs: 1.2, f: { hilt: .7 } }, walk: { knee0: .32, fps: .84, bounce: -.42, f: { hilt: .8 } }, fidgets: ['glance', 'weightShift'] },
  melancholy: { name: 'Melancholy', group: 'mood', about: 'Long sighs, eyes on the floor, a slow and heavy walk.',
    all: { bow: 1.05, lean: .06 }, idle: { period: 1.4, breath: .4, f: { dangle: .5 }, b: { dangle: .5 } },
    walk: { fps: .6, speed: .8, swing: -.28, stride: -.16 }, run: { fps: .84, speed: .9 }, fidgets: ['sigh', 'lookDown'] },
  menacing: { name: 'Menacing', group: 'mood', about: 'Leans in, arms still, cracks his neck and knuckles. Slow, long, heavy strides.',
    all: { lean: .2, chest: .11, bow: .38 }, idle: { breath: -.3, legs: 1, knee: .28 },
    walk: { fps: .52, stride: .32, bounce: -.42, swing: -.35, speed: .85, heavy: .52 }, fidgets: ['neckCrack', 'knuckles'] },
  serene: { name: 'Serene', group: 'mood', about: 'Hands tucked into his sleeves, deep slow breaths, a glide of a walk.',
    all: { bow: .3 }, idle: { period: 1.5, breath: .2, every: 2, f: { sleeves: 1 }, b: { sleeves: 1 } },
    walk: { fps: .68, bounce: -.56, swing: -.28, f: { sleeves: 1 }, b: { sleeves: 1 } }, fidgets: ['nod'] },

  // -- quirks: one habit each, to layer on anything
  hatTipper: { name: 'Hat tipper', group: 'quirk', about: 'Keeps tugging the brim of his hat down.', idle: { every: -.5 }, fidgets: ['hatTip'] },
  hiltFiddler: { name: 'Hilt fiddler', group: 'quirk', about: 'His hand keeps drifting to the sword: thumbing the guard, checking it\'s there.',
    idle: { f: { hilt: .4 } }, fidgets: ['hiltThumb', 'hiltCheck'] },
  neckCracker: { name: 'Neck cracker', group: 'quirk', about: 'Tips his head over and snaps it back.', fidgets: ['neckCrack'] },
  shoulderRoller: { name: 'Shoulder roller', group: 'quirk', about: 'Rolls the stiffness out of his shoulders.', fidgets: ['shoulderRoll'] },
  footTapper: { name: 'Foot tapper', group: 'quirk', about: 'Taps his front foot, impatient.', fidgets: ['footTap'] },
  stretcher: { name: 'Stretcher', group: 'quirk', about: 'Stretches his arms up over his head.', fidgets: ['stretch'] },
  sigher: { name: 'Sigher', group: 'quirk', about: 'Lets out long sighs.', fidgets: ['sigh'] },
  glancer: { name: 'Glancer', group: 'quirk', about: 'Keeps looking back over his shoulder.', idle: { every: -1 }, fidgets: ['glance'] },
  hummer: { name: 'Hummer', group: 'quirk', about: 'Sways to a tune only he can hear, and walks to its beat.',
    idle: { sway: 1.56, swayLean: .05, bob: .4 }, walk: { rock: .96, bounce: .42 } },
  knuckleCracker: { name: 'Knuckle cracker', group: 'quirk', about: 'Brings his hands together and cracks his knuckles.', fidgets: ['knuckles'] },
  vain: { name: 'Vain', group: 'quirk', about: 'Always tidying: straightens the mantle, brushes off a shoulder, sets the hat.',
    all: { chest: -.07 }, idle: { every: -1 }, fidgets: ['fixMantle', 'dustOff', 'hatTip'] },
  scratcher: { name: 'Head scratcher', group: 'quirk', about: 'Scratches the back of his head, puzzled.', fidgets: ['scratch'] },

  // -- body: age, injury, build
  limping: { name: 'Limping', group: 'body', about: 'Favours his near leg: a short stiff step, then a dip onto the good one.',
    idle: { lean: -.04, legs: .5 }, walk: { limp: 1, fps: .76, speed: .8 }, run: { limp: .6, speed: .85 } },
  elder: { name: 'Elder', group: 'body', about: 'Stooped, hands behind the back, short careful steps.',
    all: { lean: .36, bow: .52, chest: .18 }, idle: { knee: .35, period: 1.2, b: { behind: 1 } },
    walk: { stride: -.32, lift: -.39, fps: .68, speed: .7, swing: -.28, b: { behind: 1 } }, run: { speed: .8, fps: .76, lift: -.52 }, fidgets: ['nod'] },
  drunk: { name: 'Drunk', group: 'body', about: 'Sways, lurches, loses his footing and catches it. Weaves as he walks.',
    idle: { sway: 2.6, swayLean: .1, jitter: .72 }, walk: { wobble: 1, fps: .84, speed: .85 }, run: { wobble: .6 }, fidgets: ['stumble'] },
  lumbering: { name: 'Lumbering', group: 'body', about: 'A big man\'s weight: planted wide, arms held off the body, a slow rolling gait.',
    all: { lean: .12, chest: .07 }, idle: { legs: 2.5, knee: .42, breath: .4, period: 1.2, fa: [.15, 0], ba: [-.15, 0] },
    walk: { stride: .32, fps: .52, heavy: 1.56, rock: .96, speed: .9, swing: .14 }, run: { fps: .68, heavy: 1.3 } },
  nimble: { name: 'Nimble', group: 'body', about: 'Wiry and quick, light on bent knees, flexing his hand.',
    idle: { knee: .35, bob: .4, period: .85 }, walk: { fps: 1.32, stride: -.13, lift: .33, bounce: -.28 }, run: { fps: 1.16, speed: 1.1, lean: .12 }, fidgets: ['toes', 'flexHand'] },
  wounded: { name: 'Wounded', group: 'body', about: 'Clutches his side, breathes fast and shallow, limps.',
    all: { bow: .6, lean: .2 }, idle: { breath: .5, period: .8, knee: .28, f: { clutch: 1 } },
    walk: { limp: .5, fps: .68, speed: .75, heavy: .65, f: { clutch: 1 } }, run: { limp: .4, speed: .85, f: { clutch: .8 } }, fidgets: ['sigh'] },

  // -- discipline: how he was trained
  shinobi: { name: 'Shinobi', group: 'discipline', about: 'Low and silent, hand on the hilt. Runs bent double with both arms swept back.',
    all: { lean: .3, bow: .3 }, idle: { knee: .98, legs: 1, f: { hilt: 1 } }, walk: { knee0: .72, bounce: -.7, fps: .84, speed: .9, f: { hilt: 1 }, b: { behind: .4 } },
    run: { lean: .7, swing: -.7, f: { trail: 1 }, b: { trail: 1 } } },
  duelist: { name: 'Duelist', group: 'discipline', about: 'One hand on the hilt, the other on the scabbard, side-on and measured.',
    all: { lean: .04 }, idle: { legs: 1.2, knee: .28, f: { hilt: 1 }, b: { scabbard: 1 } }, walk: { fps: .84, bounce: -.28, f: { hilt: 1 }, b: { scabbard: 1 } },
    run: { f: { hilt: .8 } }, fidgets: ['hiltCheck'] },
  monk: { name: 'Monk', group: 'discipline', about: 'Palms together, a slow breath, a quiet walk in prayer.',
    all: { bow: .45 }, idle: { breath: -.2, period: 1.3, f: { pray: 1 }, b: { pray: 1 } }, walk: { fps: .76, bounce: -.42, f: { pray: .8 }, b: { pray: .8 } }, fidgets: ['nod'] },
  brawler: { name: 'Brawler', group: 'discipline', about: 'Fists up, bouncing on his toes, rolling his shoulders.',
    all: { lean: .2, bow: .22 }, idle: { bob: .8, period: .7, knee: .42, legs: 1.5, f: { fists: 1 }, b: { fists: 1 } },
    walk: { rock: 1.28, bounce: .56, f: { fists: .7 }, b: { fists: .7 } }, fidgets: ['shoulderRoll', 'knuckles'] },
  wanderer: { name: 'Wanderer', group: 'discipline', about: 'Arms tucked in his sleeves, an easy sway, a long road ahead.',
    all: { lean: .04 }, idle: { sway: .65, f: { sleeves: 1 }, b: { sleeves: 1 } }, walk: { fps: .76, bounce: .14, f: { sleeves: 1 }, b: { sleeves: 1 } }, fidgets: ['glance'] },
  shadow: { name: 'Shadow', group: 'discipline', about: 'Sunk low and dead still; glides with no bob at all.',
    all: { lean: .16 }, idle: { knee: .56, breath: -.5, every: 4 }, walk: { bounce: -1.4, lift: -.13, knee0: .48, fps: .84 }, run: { bounce: -1.4, lean: .12 } },
  scholar: { name: 'Scholar', group: 'discipline', about: 'Hand at his chin, lost in thought. Walks with his hands behind him, head bent.',
    all: { bow: .45 }, idle: { f: { chin: 1 } }, walk: { fps: .76, bow: .15, f: { behind: 1 }, b: { behind: 1 } }, fidgets: ['nod', 'scratch'] },
  veteran: { like: 'grim', name: 'Veteran', group: 'discipline', about: 'Grim, plus an old wound: the same set jaw and hand on the hilt, with a slight limp.',
    walk: { limp: .35 }, fidgets: ['shoulderRoll'] },
};
export const GROUPS = ['bearing', 'energy', 'mood', 'quirk', 'body', 'discipline'];

// ---- Characters: ready-made mixes, and a record of the ones we like ----
export const PRESETS = {
  'The ronin (as he is)': [],
  'Old master': [['elder', 1], ['serene', .6], ['hatTipper', 1]],
  'Drunken master': [['drunk', 1], ['cheerful', .6]],
  'Bandit captain': [['cocky', 1], ['heavy', .7], ['neckCracker', 1]],
  'Hunted man': [['nervous', 1], ['wounded', .5]],
  'Bodyguard': [['grim', 1], ['soldier', .5], ['knuckleCracker', 1]],
  'Ghost of the road': [['shadow', 1], ['wanderer', .7]],
  'Young hothead': [['eager', 1], ['cocky', .6], ['footTapper', 1]],
};
